function J_heel = J_heel(in1)
%J_HEEL
%    J_HEEL = J_HEEL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Oct-2020 21:07:10

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t11 = atan(3.472941176470588e-1);
t12 = atan(2.87940379403794);
t14 = 7.724785424827963e+16;
t3 = cos(t2);
t4 = sin(t2);
t5 = q_t3+q_t4+t2;
t16 = -t12;
t6 = cos(t5);
t7 = q_t5+t5;
t8 = sin(t5);
t13 = t3.*4.453122e-1;
t15 = t4.*4.453122e-1;
t9 = sin(t7);
t10 = cos(t7);
t17 = -t15;
t18 = t6.*4.453122e-1;
t19 = t8.*4.453122e-1;
t24 = q_t6+t7+t11;
t26 = q_t6+t7+t16;
t20 = t10.*4.60062e-1;
t21 = t9.*4.60062e-1;
t22 = -t19;
t25 = cos(t24);
t27 = cos(t26);
t23 = -t21;
t28 = t14.*t25.*1.06581410364015e-18;
t30 = t14.*t27.*1.06581410364015e-18;
t29 = -t28;
t31 = -t30;
t32 = t22+t23+t29;
t33 = t18+t20+t31;
J_heel = reshape([t17+t32-sin(q_t1).*4.60062e-1,t13+t33+cos(q_t1).*4.60062e-1,0.0,t17+t32,t13+t33,0.0,t32,t33,0.0,t32,t33,0.0,t23+t29,t20+t31,0.0,t29,t31,0.0],[3,6]);
