function J_heel = J_heel(in1)
%J_HEEL
%    J_HEEL = J_HEEL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Jan-2021 01:34:46

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t20 = atan(5.774051282051282e-1);
t21 = 6.895773429086878e+18;
t3 = cos(t2);
t4 = sin(t2);
t5 = q_t3+q_t4+t2;
t6 = cos(t5);
t7 = q_t5+t5;
t8 = sin(t5);
t11 = t3.*4.165e-1;
t12 = t4.*4.165e-1;
t9 = sin(t7);
t10 = cos(t7);
t13 = -t12;
t14 = t6.*4.165e-1;
t15 = t8.*4.165e-1;
t22 = q_t6+t7+t20;
t16 = t10.*4.182e-1;
t17 = t9.*4.182e-1;
t18 = -t15;
t23 = cos(t22);
t24 = sin(t22);
t19 = -t17;
t25 = (t21.*t23)./9.007199254740992e+19;
t26 = (t21.*t24)./9.007199254740992e+19;
t27 = -t25;
t28 = -t26;
t29 = t14+t16+t28;
t30 = t18+t19+t27;
J_heel = reshape([t13+t30-sin(q_t1).*4.182e-1,t11+t29+cos(q_t1).*4.182e-1,0.0,t13+t30,t11+t29,0.0,t30,t29,0.0,t30,t29,0.0,t19+t27,t16+t28,0.0,t27,t28,0.0],[3,6]);
