function dGrf_heel_c1_dfx = dGrf_heel_c1_dfx(Fx)
%DGRF_HEEL_C1_DFX
%    DGRF_HEEL_C1_DFX = DGRF_HEEL_C1_DFX(FX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Apr-2021 00:43:42

dGrf_heel_c1_dfx = 1.0;
