function dJ_q5 = dJ_heel5(in1)
%DJ_HEEL5
%    DJ_Q5 = DJ_HEEL5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Apr-2021 13:30:43

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4+q5;
t9 = atan(5.774051282051283e-1);
t10 = 1.546478599905513e+18;
t3 = sin(t2);
t4 = cos(t2);
t11 = q6+t2+t9;
t5 = t4.*4.4835e-1;
t6 = t3.*4.4835e-1;
t12 = cos(t11);
t13 = sin(t11);
t7 = -t5;
t8 = -t6;
t14 = t10.*t12.*5.329070518200751e-20;
t15 = t10.*t13.*5.329070518200751e-20;
t16 = -t14;
t17 = t7+t15;
t18 = t8+t16;
dJ_q5 = reshape([t17,t18,0.0,t17,t18,0.0,t17,t18,0.0,t17,t18,0.0,t17,t18,0.0,t15,t16,0.0],[3,6]);
