function dTau_heel_dfx = dTau_heel_dfx(in1,in2,Fx,H,k,cmax,dmax,sampT)
%DTAU_HEEL_DFX
%    DTAU_HEEL_DFX = DTAU_HEEL_DFX(IN1,IN2,FX,H,K,CMAX,DMAX,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Oct-2020 16:02:10

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t3 = sin(t2);
t4 = q_t3+q_t4+t2;
t5 = q_t5+t4;
t6 = sin(t4);
t8 = t3.*4.453122e-1;
t7 = sin(t5);
t9 = -t8;
t10 = q_t6+t5+4.751930427460668e-1;
t11 = t6.*4.453122e-1;
t12 = t7.*4.60062e-1;
t13 = cos(t10);
t14 = -t11;
t15 = -t12;
t16 = t13.*8.746582711697523e-2;
t17 = -t16;
t18 = t14+t15+t17;
dTau_heel_dfx = [t9+t18-sin(q_t1).*4.60062e-1,t9+t18,t18,t18,t15+t17,t17];
