function dTau_toe_pushoff_dfy = dTau_toe_pushoff_dfy(in1,in2,Fx,Fy,H,k,cmax,dmax,sampT)
%DTAU_TOE_PUSHOFF_DFY
%    DTAU_TOE_PUSHOFF_DFY = DTAU_TOE_PUSHOFF_DFY(IN1,IN2,FX,FY,H,K,CMAX,DMAX,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-Oct-2020 02:35:40

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t3 = cos(t2);
t4 = q_t3+q_t4+t2;
t5 = cos(t4);
t6 = q_t5+t4;
t8 = t3.*4.453122e-1;
t7 = cos(t6);
t9 = t5.*4.453122e-1;
t10 = q_t6+t6+4.781417504689244e-1;
t11 = t7.*4.60062e-1;
t12 = cos(t10);
t13 = t12.*1.690282735215953e-1;
t14 = t9+t11+t13;
dTau_toe_pushoff_dfy = [t8+t14+cos(q_t1).*4.60062e-1,t8+t14,t14,t14,t11+t13,t13];
