function Tau_toe_pushoff = Tau_toe_pushoff(in1,in2,Fx,Fy,H,k,cmax,dmax,sampT)
%TAU_TOE_PUSHOFF
%    TAU_TOE_PUSHOFF = TAU_TOE_PUSHOFF(IN1,IN2,FX,FY,H,K,CMAX,DMAX,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-Oct-2020 02:35:40

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t3 = cos(t2);
t4 = sin(t2);
t5 = q_t3+q_t4+t2;
t6 = cos(t5);
t7 = q_t5+t5;
t8 = sin(t5);
t11 = t3.*4.453122e-1;
t12 = t4.*4.453122e-1;
t9 = sin(t7);
t10 = cos(t7);
t13 = t6.*4.453122e-1;
t14 = t8.*4.453122e-1;
t15 = q_t6+t7-1.092654576325972;
t16 = q_t6+t7+4.781417504689244e-1;
t17 = t10.*4.60062e-1;
t18 = cos(t15);
t19 = t9.*4.60062e-1;
t20 = cos(t16);
t21 = t18.*1.690282735215953e-1;
t22 = t20.*1.690282735215953e-1;
t23 = t13+t17+t22;
t24 = t14+t19+t21;
t25 = Fy.*t23;
t26 = Fx.*t24;
t27 = -t26;
t28 = t25+t27;
Tau_toe_pushoff = [Fy.*(t11+t23+cos(q_t1).*4.60062e-1)-Fx.*(t12+t24+sin(q_t1).*4.60062e-1);-Fx.*(t12+t24)+Fy.*(t11+t23);t28;t28;-Fx.*(t19+t21)+Fy.*(t17+t22);Fx.*t18.*(-1.690282735215953e-1)+Fy.*t22];
