function dJ_q5 = dJ_hip5(in1)
%DJ_HIP5
%    DJ_Q5 = DJ_HIP5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 15:23:47

dJ_q5 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
