function dJ_q6 = dJ_heel6(in1)
%DJ_HEEL6
%    DJ_Q6 = DJ_HEEL6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 15:23:59

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = atan(5.774051282051283e-1);
t3 = 1.546478599905513e+18;
t4 = q1+q2+q3+q4+q5+q6+t2;
t5 = cos(t4);
t6 = sin(t4);
t7 = t3.*t5.*5.329070518200751e-20;
t8 = t3.*t6.*5.329070518200751e-20;
t9 = -t7;
dJ_q6 = reshape([t8,t9,t8,t9,t8,t9,t8,t9,t8,t9,t8,t9],[2,6]);
