function dHip_vel_q2 = dHip_vel_q2(in1,in2,sampT)
%DHIP_VEL_Q2
%    DHIP_VEL_Q2 = DHIP_VEL_Q2(IN1,IN2,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Apr-2021 00:41:12

dq1 = in2(:,1);
dq2 = in2(:,2);
q1 = in1(:,1);
q2 = in1(:,2);
t2 = q1+q2;
t5 = 1.0./sampT;
t3 = cos(t2);
t4 = sin(t2);
t6 = dq2.*t3.*2.24175e-1;
t7 = -t6;
dHip_vel_q2 = [t7-(dq1.*(t3.*4.4835e-1+cos(q1).*4.4835e-1))./2.0-t5.*(t4.*4.4835e-1+sin(q1).*4.4835e-1);t7-dq1.*t3.*2.24175e-1-t4.*t5.*4.4835e-1;0.0;0.0;0.0;0.0];
