function dJ_q5 = dJ_toe5(in1)
%DJ_TOE5
%    DJ_Q5 = DJ_TOE5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Apr-2021 12:57:39

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4+q5;
t9 = atan(4.618051608502898e-1);
t10 = atan(2.165415384615385);
t11 = 1.1978829188531e+18;
t3 = sin(t2);
t4 = cos(t2);
t12 = -t10;
t13 = q6+t2+t9;
t5 = t4.*4.4835e-1;
t6 = t3.*4.4835e-1;
t14 = sin(t13);
t15 = q6+t2+t12;
t7 = -t5;
t8 = -t6;
t16 = sin(t15);
t17 = (t11.*t14)./7.0368744177664e+18;
t18 = -t17;
t19 = (t11.*t16)./7.0368744177664e+18;
t20 = t8+t18;
t21 = t7+t19;
dJ_q5 = reshape([t21,t20,0.0,t21,t20,0.0,t21,t20,0.0,t21,t20,0.0,t21,t20,0.0,t19,t18,0.0],[3,6]);
