function dJ_q4 = J_hip4(in1)
%J_HIP4
%    DJ_Q4 = J_HIP4(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Apr-2021 01:23:40

dJ_q4 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
