function dTau_toe_pushoff_dfy = dTau_toe_pushoff_dfy(in1,in2,Fx,Fy,H,k,cmax,dmax,sampT)
%DTAU_TOE_PUSHOFF_DFY
%    DTAU_TOE_PUSHOFF_DFY = DTAU_TOE_PUSHOFF_DFY(IN1,IN2,FX,FY,H,K,CMAX,DMAX,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Dec-2020 16:46:11

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t9 = atan(5.18251222829003e-1);
t10 = 1.903089174117337e+18;
t3 = cos(t2);
t4 = q_t3+q_t4+t2;
t5 = cos(t4);
t6 = q_t5+t4;
t8 = t3.*4.453122e-1;
t7 = cos(t6);
t11 = t5.*4.453122e-1;
t13 = q_t6+t6+t9;
t12 = t7.*4.60062e-1;
t14 = cos(t13);
t15 = (t10.*t14)./1.125899906842624e+19;
t16 = t11+t12+t15;
dTau_toe_pushoff_dfy = [t8+t16+cos(q_t1).*4.60062e-1,t8+t16,t16,t16,t12+t15,t15];
