function dGrf_toe_c1_dfx = dGrf_toe_c1_dfx(Fx)
%DGRF_TOE_C1_DFX
%    DGRF_TOE_C1_DFX = DGRF_TOE_C1_DFX(FX)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Aug-2021 23:37:22

dGrf_toe_c1_dfx = 1.0;
