function dGrf_heel_c2_dfx = dGrf_heel_c2_dfx(Fx)
%DGRF_HEEL_C2_DFX
%    DGRF_HEEL_C2_DFX = DGRF_HEEL_C2_DFX(FX)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Aug-2021 23:37:00

dGrf_heel_c2_dfx = -1.0;
