function dJ_q3 = dJ_hip3(in1)
%DJ_HIP3
%    DJ_Q3 = DJ_HIP3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Apr-2021 13:30:36

dJ_q3 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
