function out1 = dJ_heel6(in1)
%DJ_HEEL6
%    OUT1 = DJ_HEEL6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 18:39:26

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4+q5+q6+5.236399188825582e-1;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3.*8.241293513784844e-2;
t6 = t4.*8.241293513784844e-2;
t7 = -t5;
out1 = reshape([t6,t7,t6,t7,t6,t7,t6,t7,t6,t7,t6,t7],[2,6]);
