function dJ_q5 = dJ_hip5(in1)
%DJ_HIP5
%    DJ_Q5 = DJ_HIP5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Apr-2021 13:30:45

dJ_q5 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
