function out1 = dJ_heel5(in1)
%DJ_HEEL5
%    OUT1 = DJ_HEEL5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 18:39:11

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4+q5;
t3 = sin(t2);
t4 = cos(t2);
t9 = q6+t2+5.236399188825582e-1;
t5 = t4.*4.4835e-1;
t6 = t3.*4.4835e-1;
t10 = cos(t9);
t11 = sin(t9);
t7 = -t5;
t8 = -t6;
t12 = t10.*8.241293513784844e-2;
t13 = t11.*8.241293513784844e-2;
t14 = -t12;
t15 = t7+t13;
t16 = t8+t14;
out1 = reshape([t15,t16,t15,t16,t15,t16,t15,t16,t15,t16,t13,t14],[2,6]);
