function dJ_q1 = dJ_hip1(in1)
%DJ_HIP1
%    DJ_Q1 = DJ_HIP1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Apr-2021 13:30:41

q1 = in1(:,1);
q2 = in1(:,2);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3.*4.4835e-1;
t6 = t4.*4.4835e-1;
t7 = -t5;
t8 = -t6;
dJ_q1 = reshape([t7-cos(q1).*4.4835e-1,t8-sin(q1).*4.4835e-1,0.0,t7,t8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
