function out1 = dJ_heel4(in1)
%DJ_HEEL4
%    OUT1 = DJ_HEEL4(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 18:38:54

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4;
t3 = cos(t2);
t4 = q5+t2;
t5 = sin(t2);
t6 = sin(t4);
t7 = cos(t4);
t8 = t3.*4.4835e-1;
t9 = t5.*4.4835e-1;
t16 = q6+t4+5.236399188825582e-1;
t10 = t7.*4.4835e-1;
t11 = t6.*4.4835e-1;
t12 = -t8;
t13 = -t9;
t17 = cos(t16);
t18 = sin(t16);
t14 = -t10;
t15 = -t11;
t19 = t17.*8.241293513784844e-2;
t20 = t18.*8.241293513784844e-2;
t21 = -t19;
t22 = t12+t14+t20;
t23 = t13+t15+t21;
out1 = reshape([t22,t23,t22,t23,t22,t23,t22,t23,t14+t20,t15+t21,t20,t21],[2,6]);
