function out1 = dJ_toe2(in1)
%DJ_TOE2
%    OUT1 = DJ_TOE2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 18:35:50

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = q3+q4+t2;
t6 = cos(t5);
t7 = q5+t5;
t8 = sin(t5);
t11 = t3.*4.4835e-1;
t12 = t4.*4.4835e-1;
t9 = sin(t7);
t10 = cos(t7);
t13 = -t11;
t14 = -t12;
t15 = t6.*4.4835e-1;
t16 = t8.*4.4835e-1;
t23 = q6+t7+4.32627617569072e-1;
t24 = q6+t7-1.138168709225825;
t17 = t10.*4.4835e-1;
t18 = t9.*4.4835e-1;
t19 = -t15;
t20 = -t16;
t25 = sin(t23);
t26 = sin(t24);
t21 = -t17;
t22 = -t18;
t27 = t25.*1.702294012564352e-1;
t28 = t26.*1.702294012564352e-1;
t29 = -t27;
t31 = t19+t21+t28;
t30 = t20+t22+t29;
t33 = t13+t31;
t32 = t14+t30;
out1 = reshape([t33,t32,t33,t32,t31,t30,t31,t30,t21+t28,t22+t29,t28,t29],[2,6]);
