function out1 = dJ_toe4(in1)
%DJ_TOE4
%    OUT1 = DJ_TOE4(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 18:36:28

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4;
t3 = cos(t2);
t4 = q5+t2;
t5 = sin(t2);
t6 = sin(t4);
t7 = cos(t4);
t8 = t3.*4.4835e-1;
t9 = t5.*4.4835e-1;
t16 = q6+t4+4.32627617569072e-1;
t17 = q6+t4-1.138168709225825;
t10 = t7.*4.4835e-1;
t11 = t6.*4.4835e-1;
t12 = -t8;
t13 = -t9;
t18 = sin(t16);
t19 = sin(t17);
t14 = -t10;
t15 = -t11;
t20 = t18.*1.702294012564352e-1;
t21 = t19.*1.702294012564352e-1;
t22 = -t20;
t24 = t12+t14+t21;
t23 = t13+t15+t22;
out1 = reshape([t24,t23,t24,t23,t24,t23,t24,t23,t14+t21,t15+t22,t21,t22],[2,6]);
