function out1 = dJ_toe6(in1)
%DJ_TOE6
%    OUT1 = DJ_TOE6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 18:37:10

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4+q5+q6+4.32627617569072e-1;
t3 = q1+q2+q3+q4+q5+q6-1.138168709225825;
t4 = sin(t2);
t5 = sin(t3);
t6 = t4.*1.702294012564352e-1;
t7 = t5.*1.702294012564352e-1;
t8 = -t6;
out1 = reshape([t7,t8,t7,t8,t7,t8,t7,t8,t7,t8,t7,t8],[2,6]);
