function out1 = dJ_toe5(in1)
%DJ_TOE5
%    OUT1 = DJ_TOE5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2021 18:36:47

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4+q5;
t3 = sin(t2);
t4 = cos(t2);
t9 = q6+t2+4.32627617569072e-1;
t10 = q6+t2-1.138168709225825;
t5 = t4.*4.4835e-1;
t6 = t3.*4.4835e-1;
t11 = sin(t9);
t12 = sin(t10);
t7 = -t5;
t8 = -t6;
t13 = t11.*1.702294012564352e-1;
t14 = t12.*1.702294012564352e-1;
t15 = -t13;
t17 = t7+t14;
t16 = t8+t15;
out1 = reshape([t17,t16,t17,t16,t17,t16,t17,t16,t17,t16,t14,t15],[2,6]);
