function dJ_q3 = J_hip3(in1)
%J_HIP3
%    DJ_Q3 = J_HIP3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Apr-2021 01:23:40

dJ_q3 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,6]);
