function [b,bExo] = work_cal(result,result_exo,sup_eff,rec_eff)
%% calculate the positive work and negative work
data = result.data;
w_all = [sum(data.base.x_avg.^2,2),...
         sum(data.eff_hip.x_avg.^2,2),...
         sum(data.eff_kne.x_avg.^2,2),...
         sum(data.eff_ank.x_avg.^2,2),...
         sum(data.eff_hk.x_avg.^2,2),...
         sum(data.eff_ha.x_avg.^2,2),...
         sum(data.eff_ka.x_avg.^2,2)];
w_all = w_all(4:6,:);
w_neg = [sum(data.base.neg_u.^2,2),...
         sum(data.eff_hip.neg_u.^2,2),...
         sum(data.eff_kne.neg_u.^2,2),...
         sum(data.eff_ank.neg_u.^2,2),...
         sum(data.eff_hk.neg_u.^2,2),...
         sum(data.eff_ha.neg_u.^2,2),...
         sum(data.eff_ka.neg_u.^2,2)];
w_pos = w_all-w_neg;
 

w_ratio=w_neg./w_pos;
w_rec = w_all-w_neg*(sup_eff+sup_eff*rec_eff);
w_rec = sum(w_rec,1)/result.hipLen;
w_rec_ka = sum(w_all,1)/result.hipLen-(sup_eff+sup_eff*rec_eff)*sum(w_neg(2:3,:),1)/result.hipLen;
w_tot = sum(w_all,1)/result.hipLen;
w_red = (w_tot-w_rec)./w_tot; % work reduce percentage
w_red_ka = (w_tot-w_rec_ka)./w_tot;
w_work = sum(w_all,1);
%% data with exo weight
dataExo = result_exo.data;
wExo_all = [sum(dataExo.base.x_avg.^2,2),...
         sum(dataExo.eff_hip.x_avg.^2,2),...
         sum(dataExo.eff_kne.x_avg.^2,2),...
         sum(dataExo.eff_ank.x_avg.^2,2),...
         sum(dataExo.eff_hk.x_avg.^2,2),...
         sum(dataExo.eff_ha.x_avg.^2,2),...
         sum(dataExo.eff_ka.x_avg.^2,2)];
wExo_all = wExo_all(4:6,:);
wExo_neg = [sum(dataExo.base.neg_u.^2,2),...
         sum(dataExo.eff_hip.neg_u.^2,2),...
         sum(dataExo.eff_kne.neg_u.^2,2),...
         sum(dataExo.eff_ank.neg_u.^2,2),...
         sum(dataExo.eff_hk.neg_u.^2,2),...
         sum(dataExo.eff_ha.neg_u.^2,2),...
         sum(dataExo.eff_ka.neg_u.^2,2)];
wExo_pos = wExo_all-wExo_neg;
wExo_rec = wExo_all-wExo_neg*(sup_eff+sup_eff*rec_eff);
wExo_rec = sum(wExo_rec,1)/result_exo.hipLen;
wExo_rec_ka = sum(wExo_all,1)/result.hipLen-(sup_eff+sup_eff*rec_eff)*sum(wExo_neg(2:3,:),1)/result.hipLen;
wExo_tot = sum(wExo_all,1)/result_exo.hipLen;
wExo_ratio=wExo_neg./wExo_pos;
wExo_red = (wExo_tot-wExo_rec)./wExo_tot; % work reduce percentage
wExo_red_ka = (wExo_tot-wExo_rec_ka)./wExo_tot;
wExo_work = sum(wExo_all,1);
b = table(w_all(1,:).',w_ratio(1,:).',w_all(2,:).',w_ratio(2,:).',w_all(3,:).',w_ratio(3,:).',w_work.',w_tot.',w_rec.',w_red.',w_rec_ka.',w_red_ka.',...
         'VariableNames',{'Hip','Hip N/P','Knee','Knee N/P','Ank','Ankle N/P','W tot','W tot(scaled)','W rec(scaled)','Red(%)','W rec KA (scaled)','Red KA(%)'},...
          'RowNames',{'Baseline','Eff Hip','Eff Knee','Eff Ank','Eff HK', 'Eff HA', 'Eff KA'});
bExo = table(wExo_all(1,:).',wExo_ratio(1,:).',wExo_all(2,:).',wExo_ratio(2,:).',wExo_all(3,:).',wExo_ratio(3,:).',wExo_work.',wExo_tot.',wExo_rec.',wExo_red.',wExo_rec_ka.',wExo_red_ka.',...
         'VariableNames',{'Hip all','Hip N/P','Knee all','Knee N/P','Ank all','Ankle N/P','W tot','W tot(scaled)','W rec(scaled)','Red(%)','W rec KA (scaled)','Red KA(%)'},...
          'RowNames',{'Baseline','Eff Hip','Eff Knee','Eff Ank','Eff HK', 'Eff HA', 'Eff KA'});
end