function dJ_q4 = dJ_hip4(in1)
%DJ_HIP4
%    DJ_Q4 = DJ_HIP4(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Aug-2021 23:37:00

dJ_q4 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
