function dJ_q3 = dJ_hip3(in1)
%DJ_HIP3
%    DJ_Q3 = DJ_HIP3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Aug-2021 23:36:59

dJ_q3 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
