function dJ_q3 = dJ_hip3(in1)
%DJ_HIP3
%    DJ_Q3 = DJ_HIP3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Apr-2021 00:40:07

dJ_q3 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
