function dJ_q5 = dJ_hip5(in1)
%DJ_HIP5
%    DJ_Q5 = DJ_HIP5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Apr-2021 00:40:07

dJ_q5 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
