function dHip_vel_q1 = dHip_vel_q1(in1,in2,sampT)
%DHIP_VEL_Q1
%    DHIP_VEL_Q1 = DHIP_VEL_Q1(IN1,IN2,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Jan-2021 22:49:29

q_t1 = in1(:,1);
q_t2 = in1(:,2);
qd_t1 = in2(:,1);
qd_t2 = in2(:,2);
t2 = q_t1+q_t2;
t5 = 1.0./sampT;
t3 = cos(t2);
t4 = sin(t2);
t6 = qd_t2.*t3.*2.24175e-1;
t7 = -t6;
dHip_vel_q1 = [t7-(qd_t1.*(t3.*4.4835e-1+cos(q_t1).*4.5018e-1))./2.0+t5.*(t4.*4.4835e-1+sin(q_t1).*4.5018e-1);t7-qd_t1.*t3.*2.24175e-1+t4.*t5.*4.4835e-1;0.0;0.0;0.0;0.0];
