function dJ_q6 = dJ_toe6(in1)
%DJ_TOE6
%    DJ_Q6 = DJ_TOE6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Apr-2021 22:34:19

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = atan(4.618051608502898e-1);
t3 = atan(2.165415384615385);
t4 = 1.1978829188531e+18;
t5 = -t3;
t6 = q1+q2+q3+q4+q5+q6+t2;
t7 = sin(t6);
t8 = q1+q2+q3+q4+q5+q6+t5;
t9 = sin(t8);
t10 = (t4.*t7)./7.0368744177664e+18;
t11 = -t10;
t12 = (t4.*t9)./7.0368744177664e+18;
dJ_q6 = reshape([t12,t11,t12,t11,t12,t11,t12,t11,t12,t11,t12,t11],[2,6]);
