function dTau_toe_pushoff_dfx = dTau_toe_pushoff_dfx(in1,in2,Fx,Fy,H,k,cmax,dmax,sampT)
%DTAU_TOE_PUSHOFF_DFX
%    DTAU_TOE_PUSHOFF_DFX = DTAU_TOE_PUSHOFF_DFX(IN1,IN2,FX,FY,H,K,CMAX,DMAX,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Jan-2021 01:44:17

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t14 = atan(2.165415384615384);
t15 = 4.451149643825727e+17;
t3 = sin(t2);
t4 = q_t3+q_t4+t2;
t16 = -t14;
t5 = q_t5+t4;
t6 = sin(t4);
t8 = t3.*4.165e-1;
t7 = sin(t5);
t9 = -t8;
t10 = t6.*4.165e-1;
t17 = q_t6+t5+t16;
t11 = t7.*4.182e-1;
t12 = -t10;
t18 = cos(t17);
t13 = -t11;
t19 = (t15.*t18)./2.81474976710656e+18;
t20 = -t19;
t21 = t12+t13+t20;
dTau_toe_pushoff_dfx = [t9+t21-sin(q_t1).*4.182e-1,t9+t21,t21,t21,t13+t20,t20];
