function dTau_toe_pushoff_dfy = dTau_toe_pushoff_dfy(in1,in2,Fx,Fy,H,k,cmax,dmax,sampT)
%DTAU_TOE_PUSHOFF_DFY
%    DTAU_TOE_PUSHOFF_DFY = DTAU_TOE_PUSHOFF_DFY(IN1,IN2,FX,FY,H,K,CMAX,DMAX,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Jan-2021 01:50:11

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t11 = atan(4.618051608502899e-1);
t12 = 4.451149643825727e+17;
t3 = cos(t2);
t4 = q_t3+q_t4+t2;
t5 = cos(t4);
t6 = q_t5+t4;
t8 = t3.*4.165e-1;
t7 = cos(t6);
t9 = t5.*4.165e-1;
t13 = q_t6+t6+t11;
t10 = t7.*4.182e-1;
t14 = cos(t13);
t15 = (t12.*t14)./2.81474976710656e+18;
t16 = t9+t10+t15;
dTau_toe_pushoff_dfy = [t8+t16+cos(q_t1).*4.182e-1,t8+t16,t16,t16,t10+t15,t15];
