function dGrf_toe_c2_dfx = dGrf_toe_c2_dfx(Fx)
%DGRF_TOE_C2_DFX
%    DGRF_TOE_C2_DFX = DGRF_TOE_C2_DFX(FX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Apr-2021 00:41:02

dGrf_toe_c2_dfx = -1.0;
