function dGrf_heel_c2_dfx = dGrf_heel_c2_dfx(in1,in2,Fx,H,k,cmax,dmax,us,sampT)
%DGRF_HEEL_C2_DFX
%    DGRF_HEEL_C2_DFX = DGRF_HEEL_C2_DFX(IN1,IN2,FX,H,K,CMAX,DMAX,US,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Jan-2021 15:18:00

dGrf_heel_c2_dfx = Fx.*2.0;
