function dJ_q6 = dJ_hip6(in1)
%DJ_HIP6
%    DJ_Q6 = DJ_HIP6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Apr-2021 18:38:08

dJ_q6 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
