function dJ_q6 = dJ_hip6(in1)
%DJ_HIP6
%    DJ_Q6 = DJ_HIP6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Apr-2021 22:34:19

dJ_q6 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
