function dGrf_heel_c1_dfx = dGrf_heel_c1_dfx(Fx)
%DGRF_HEEL_C1_DFX
%    DGRF_HEEL_C1_DFX = DGRF_HEEL_C1_DFX(FX)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 15:30:35

dGrf_heel_c1_dfx = 1.0;
