function dTau_toe_pushoff_dfx = dTau_toe_pushoff_dfx(in1,in2,Fx,Fy,H,k,cmax,dmax,sampT)
%DTAU_TOE_PUSHOFF_DFX
%    DTAU_TOE_PUSHOFF_DFX = DTAU_TOE_PUSHOFF_DFX(IN1,IN2,FX,FY,H,K,CMAX,DMAX,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 15:23:56

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2;
t14 = atan(2.165415384615385);
t15 = 1.1978829188531e+18;
t3 = sin(t2);
t4 = q3+q4+t2;
t16 = -t14;
t5 = q5+t4;
t6 = sin(t4);
t8 = t3.*4.4835e-1;
t7 = sin(t5);
t9 = -t8;
t10 = t6.*4.4835e-1;
t17 = q6+t5+t16;
t11 = t7.*4.4835e-1;
t12 = -t10;
t18 = cos(t17);
t13 = -t11;
t19 = (t15.*t18)./7.0368744177664e+18;
t20 = -t19;
t21 = t12+t13+t20;
dTau_toe_pushoff_dfx = [t9+t21-sin(q1).*4.4835e-1,t9+t21,t21,t21,t13+t20,t20];
