function dGrf_toe_c6_s = dGrf_toe_c6_s(in1,H)
%DGRF_TOE_C6_S
%    DGRF_TOE_C6_S = DGRF_TOE_C6_S(IN1,H)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Aug-2020 12:42:26

dGrf_toe_c6_s = 1.0;
