function dGrf_heel_c6_s = dGrf_heel_c6_s(in1,H)
%DGRF_HEEL_C6_S
%    DGRF_HEEL_C6_S = DGRF_HEEL_C6_S(IN1,H)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-Sep-2020 10:02:19

dGrf_heel_c6_s = 1.0;
