function Grf_heel_c6 = Grf_heel_c6(in1,s,H)
%GRF_HEEL_C6
%    GRF_HEEL_C6 = GRF_HEEL_C6(IN1,S,H)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-Sep-2020 10:02:27

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = cos(q_t1);
t3 = cos(q_t2);
t4 = cos(q_t3);
t5 = cos(q_t4);
t6 = cos(q_t5);
t7 = sin(q_t1);
t8 = sin(q_t2);
t9 = sin(q_t3);
t10 = sin(q_t4);
t11 = sin(q_t5);
t12 = t2.*t3;
t13 = t2.*t8;
t14 = t3.*t7;
t15 = t7.*t8;
t16 = -t15;
t17 = t13+t14;
t18 = t12+t16;
t19 = t4.*t17;
t20 = t9.*t17;
t21 = t4.*t18;
t22 = t9.*t18;
t23 = -t20;
t24 = t19+t22;
t25 = t21+t23;
t28 = -t5.*(t20-t21);
t29 = -t10.*(t20-t21);
t26 = t5.*t24;
t27 = t10.*t24;
t30 = -t27;
t31 = t26+t29;
t32 = t28+t30;
Grf_heel_c6 = s+tanh(H.*-1.0e+3+t7.*4.60062e+2+t13.*4.453122e+2+t14.*4.453122e+2+t26.*4.453122e+2+sin(q_t6).*(t11.*(t27+t5.*(t20-t21))-t6.*t31).*7.7775e+1-t11.*(t27+t5.*(t20-t21)).*4.60062e+2+t6.*t31.*4.60062e+2-t10.*(t20-t21).*4.453122e+2-cos(q_t6).*(t6.*(t27+t5.*(t20-t21))+t11.*t31).*7.7775e+1)./2.0-1.0./2.0;
