function dJ_q2 = dJ_hip2(in1)
%DJ_HIP2
%    DJ_Q2 = DJ_HIP2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    21-Apr-2021 15:23:46

q1 = in1(:,1);
q2 = in1(:,2);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3.*4.4835e-1;
t6 = t4.*4.4835e-1;
t7 = -t5;
t8 = -t6;
dJ_q2 = reshape([t7,t8,t7,t8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
