function dGrf_toe_c2_dfx = dGrf_toe_c2_dfx(in1,in2,Fx,H,k,cmax,dmax,us,sampT)
%DGRF_TOE_C2_DFX
%    DGRF_TOE_C2_DFX = DGRF_TOE_C2_DFX(IN1,IN2,FX,H,K,CMAX,DMAX,US,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Oct-2020 12:39:48

dGrf_toe_c2_dfx = Fx.*2.0;
