function dTau_toe_dfx = dTau_toe_dfx(in1,in2,Fx,H,k,cmax,dmax,sampT)
%DTAU_TOE_DFX
%    DTAU_TOE_DFX = DTAU_TOE_DFX(IN1,IN2,FX,H,K,CMAX,DMAX,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Oct-2020 12:39:48

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t9 = atan(1.929566117647059);
t11 = 1.903089174117337e+18;
t3 = sin(t2);
t4 = q_t3+q_t4+t2;
t15 = -t9;
t5 = q_t5+t4;
t6 = sin(t4);
t8 = t3.*4.453122e-1;
t7 = sin(t5);
t10 = -t8;
t12 = t6.*4.453122e-1;
t17 = q_t6+t5+t15;
t13 = t7.*4.60062e-1;
t14 = -t12;
t18 = cos(t17);
t16 = -t13;
t19 = (t11.*t18)./1.125899906842624e+19;
t20 = -t19;
t21 = t14+t16+t20;
dTau_toe_dfx = [t10+t21-sin(q_t1).*4.60062e-1,t10+t21,t21,t21,t16+t20,t20];
